config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cinnamon-pig.sh
        container: qc.acc_lousy-blue-akita
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-azure-bee.sh
        container: qc.doc_cozy-magenta-capuchin
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lime-hound.sh
        container: qc.doc_greasy-tan-dodo
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chocolate-orangutan.sh
        container: qc.lic_smelly-celadon-uguisu
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.randy-pear-nightingale.sh
        container: qc.met_freaky-xanthic-lizard
timeout: 600
