config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/filter_tools_by_repo_content
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-heliotrope-fish.sh
        container: qc.acc_crappy-goldenrod-turtle
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_readme.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-azure-gerbil.sh
        container: qc.doc_muggy-peach-dane
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pear-yak.sh
        container: qc.doc_blurry-burgundy-axolotl
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-celadon-camel.sh
        container: qc.lic_surly-indigo-deer
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-saffron-fly.sh
        container: qc.met_slimy-brass-starfish
timeout: 600
