config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-wisteria-koala.sh
        container: qc.acc_lanky-myrtle-tarsier
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-rust-rabbit.sh
        container: qc.doc_flimsy-wisteria-leopard
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-tangerine-chimpanzee.sh
        container: qc.doc_muggy-flax-toad
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-mauve-albatross.sh
        container: qc.lic_cranky-cyan-monster
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cornflower-maltese.sh
        container: qc.met_sloppy-white-gharial
timeout: 600
