config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-periwinkle-weasel.sh
        container: qc.acc_lovely-orchid-macaw
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_readme.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-peach-deer.sh
        container: qc.doc_ready-teal-cichlid
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-wheat-malamute.sh
        container: qc.doc_seedy-crimson-avocet
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-scarlet-badger.sh
        container: qc.lic_baggy-purple-tiger
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cerulean-guppy.sh
        container: qc.met_lanky-ochre-dingo
timeout: 600
