config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-orange-turkey.sh
        container: qc.acc_homey-asparagus-collie
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_readme.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-platinum-molly.sh
        container: qc.doc_nerdy-chartreuse-orangutan
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-blue-pig.sh
        container: qc.doc_snippy-persimmon-chinook
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-violet-civet.sh
        container: qc.lic_scaly-chestnut-bonobo
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amber-bombay.sh
        container: qc.met_skanky-beige-woodlouse
timeout: 600
