config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ultramarine-bracke.sh
        container: qc.acc_flimsy-goldenrod-cheetah
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_readme.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-crimson-dog.sh
        container: qc.doc_sleepy-aquamarine-dragonfly
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-buff-magpie.sh
        container: qc.doc_cranky-lime-wrasse
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-flax-ray.sh
        container: qc.lic_gamy-olivine-salamander
timeout: 600
