config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cardinal-bloodhound.sh
        container: qc.acc_cloudy-sangria-otter
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-seashell-raccoon.sh
        container: qc.doc_fuzzy-razzmatazz-macaw
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cyan-wolverine.sh
        container: qc.doc_skimpy-ivory-shark
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-flax-paradise.sh
        container: qc.lic_slaphappy-chocolate-serval
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-crimson-elephant.sh
        container: qc.met_foggy-seashell-rattlesnake
timeout: 600
