config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-orchid-sheep.sh
        container: qc.acc_greasy-corn-lobster
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-taupe-oyster.sh
        container: qc.doc_ready-apricot-fly
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-aquamarine-binturong.sh
        container: qc.doc_clammy-jade-lobster
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-smalt-opossum.sh
        container: qc.lic_trippy-orange-rat
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cobalt-coati.sh
        container: qc.met_sickly-maroon-affenpinscher
timeout: 600
