config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cream-vulture.sh
        container: qc.acc_ugly-rust-reindeer
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-beige-dachshund.sh
        container: qc.doc_sunny-apricot-axolotl
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-celadon-hare.sh
        container: qc.doc_wheezy-sepia-whippet
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-rust-fowl.sh
        container: qc.lic_baggy-pear-koala
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mustard-meerkat.sh
        container: qc.met_lovely-denim-dalmatian
timeout: 600
