config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cyan-centipede.sh
        container: qc.acc_hilly-razzmatazz-falcon
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-heliotrope-tamarin.sh
        container: qc.doc_slaphappy-corn-koala
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-teal-wolverine.sh
        container: qc.doc_skimpy-cinnabar-flounder
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-violet-catfish.sh
        container: qc.lic_lovely-orchid-dogfish
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-alizarin-chipmunk.sh
        container: qc.met_flimsy-indigo-quail
timeout: 600
