config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-puce-kakapo.sh
        container: qc.acc_bluesy-russet-gharial
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-flax-quetzal.sh
        container: qc.doc_craggy-magenta-cuscus
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.ready-amethyst-cheetah.sh
        container: qc.doc_lumpy-olive-opossum
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-scarlet-coral.sh
        container: qc.lic_smelly-myrtle-sponge
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.ready-viridian-vole.sh
        container: qc.met_muggy-cream-tang
timeout: 600
