config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-indigo-yak.sh
        container: qc.acc_surly-sepia-stingray
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-peach-woodpecker.sh
        container: qc.doc_silly-maroon-orangutan
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cornflower-flamingo.sh
        container: qc.doc_squeaky-eggplant-lobster
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-champagne-eel.sh
        container: qc.lic_droopy-gamboge-boar
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-sapphire-mayfly.sh
        container: qc.met_stinky-salmon-budgerigar
timeout: 600
